# Generated by Django 3.1.5 on 2021-01-06 00:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('celular', models.CharField(max_length=11)),
                ('dataCadastro', models.DateField(blank=True, default=datetime.datetime.now)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('Plano de Saude', 'Plano'), ('Particular', 'Particular')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento', models.CharField(blank=True, choices=[('Convenio', 'Convenio'), ('Cartão - Debito', 'Cartao de Debito'), ('Cartão - Credito', 'Cartao de Credito'), ('Dinheiro', 'Dinheiro')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serviço',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('horainicial', models.TimeField()),
                ('horafinal', models.TimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clienteagendamento', to='Agenda.cliente')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeloagendamento', to='Agenda.modelo')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Agenda.pagamento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicoagendamento', to='Agenda.serviço')),
            ],
        ),
    ]
